/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="../../adonisrc.ts" />
/// <reference path="../../config/auth.ts" />
/// <reference path="../../config/hash.ts" />
/// <reference path="../../config/logger.ts" />
/// <reference path="../../config/swagger_examples.ts" />
/// <reference path="../../config/swagger_examples/apply.ts" />
/// <reference path="../../config/swagger_examples/examples/auth.ts" />
/// <reference path="../../config/swagger_examples/operations/auth.ts" />
/// <reference path="../../config/swagger_examples/operations/index.ts" />
/// <reference path="../../config/swagger_examples/schemas/auth.ts" />
/// <reference path="../../config/swagger_examples/schemas/index.ts" />
/// <reference path="../../config/swagger_examples/types.ts" />
/// <reference path="../../config/swagger.ts" />
/// <reference path="../../config/swagger_examples/examples/gateways.ts" />
/// <reference path="../../config/swagger_examples/examples/products.ts" />
/// <reference path="../../config/swagger_examples/examples/clients.ts" />
/// <reference path="../../config/swagger_examples/examples/transactions.ts" />
/// <reference path="../../config/swagger_examples/examples/purchases.ts" />
/// <reference path="../../config/swagger_examples/operations/gateways.ts" />
/// <reference path="../../config/swagger_examples/operations/products.ts" />
/// <reference path="../../config/swagger_examples/operations/clients.ts" />
/// <reference path="../../config/swagger_examples/operations/transactions.ts" />
/// <reference path="../../config/swagger_examples/operations/purchases.ts" />
/// <reference path="../../config/swagger_examples/schemas/gateways.ts" />
/// <reference path="../../config/swagger_examples/schemas/products.ts" />
/// <reference path="../../config/swagger_examples/schemas/clients.ts" />
/// <reference path="../../config/swagger_examples/schemas/transactions.ts" />
