/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="../../adonisrc.ts" />
/// <reference path="../../config/auth.ts" />
/// <reference path="../../config/hash.ts" />
/// <reference path="../../config/logger.ts" />
/// <reference path="../../config/swagger_examples.ts" />
/// <reference path="../../config/swagger_examples/apply.ts" />
/// <reference path="../../config/swagger_examples/examples/auth.ts" />
/// <reference path="../../config/swagger_examples/operations/auth.ts" />
/// <reference path="../../config/swagger_examples/operations/index.ts" />
/// <reference path="../../config/swagger_examples/schemas/auth.ts" />
/// <reference path="../../config/swagger_examples/schemas/index.ts" />
/// <reference path="../../config/swagger_examples/types.ts" />
/// <reference path="../../config/swagger.ts" />
